# docker-compose.yml
version: '3.5'

services:
  product-service:
    restart: always # ensures the container will restart on crash
    container_name: "product-service"
    build: .
    ports:
      - 50051 # exposing this port on the docker network only, not host
    links:
      - datastore
    depends_on:
      - datastore
    networks:
      - steaks-backend-tier
      - product-tier
    environment:
      DB_HOST: "mongodb://datastore:27017"
      MICRO_ADDRESS: ":50051"

  datastore:
    image: mongo:latest
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    networks:
      - product-tier
    ports:
      - 27017
    command: mongod --logpath=/dev/null

networks:
  product-tier:
    name: product-tier
  steaks-backend-tier:
    name: steaks-backend-tier