version: '3.5'

services:
  product-service:
    restart: always
    container_name: "product-service"
    build: .
    ports:
      - 50051
    environment:
      DB_HOST: "mongodb://datastore:27017"
      MICRO_ADDRESS: ":50051"

  datastore:
    image: mongo:latest
    ports:
      - 27017

networks:
  default:
    external:
      name: steaks-backend-tier
