// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product/product.proto

package steaks_product_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Product struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount               int32    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	StorageId            int32    `protobuf:"varint,5,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Product) GetStorageId() int32 {
	if m != nil {
		return m.StorageId
	}
	return 0
}

type Response struct {
	Created              bool       `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Product              *Product   `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Products             []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_14fbc13de7c38f78, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Response) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "steaks.product.service.GetRequest")
	proto.RegisterType((*Product)(nil), "steaks.product.service.Product")
	proto.RegisterType((*Response)(nil), "steaks.product.service.Response")
}

func init() { proto.RegisterFile("proto/product/product.proto", fileDescriptor_14fbc13de7c38f78) }

var fileDescriptor_14fbc13de7c38f78 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0xdb, 0xa4, 0x17, 0xe8, 0x70, 0x43, 0x65, 0x81, 0x10, 0x51, 0xa6, 0x4e, 0x41,
	0x2a, 0x13, 0x62, 0x64, 0xa8, 0xd8, 0x90, 0x81, 0x19, 0x85, 0xf8, 0x84, 0x2c, 0xd4, 0x38, 0xd8,
	0x0e, 0x9f, 0xc0, 0x57, 0xf0, 0x2b, 0xfc, 0x1b, 0x92, 0x63, 0x03, 0x03, 0x15, 0x9d, 0x7c, 0xf7,
	0xee, 0xbd, 0xd3, 0x7b, 0xb6, 0xe1, 0xa4, 0x37, 0xda, 0xe9, 0xf3, 0xde, 0x68, 0x39, 0xb4, 0x2e,
	0x9e, 0xb5, 0x47, 0x71, 0x69, 0x1d, 0x35, 0x2f, 0xb6, 0x8e, 0xa8, 0x25, 0xf3, 0xa6, 0x5a, 0xaa,
	0x0e, 0x01, 0x36, 0xe4, 0x04, 0xbd, 0x0e, 0x64, 0x5d, 0xf5, 0xce, 0x20, 0xbb, 0x1d, 0x19, 0xb8,
	0x80, 0x44, 0x49, 0xce, 0x4a, 0xb6, 0x9a, 0x8a, 0x44, 0x49, 0x44, 0x98, 0x74, 0xcd, 0x96, 0x78,
	0x52, 0xb2, 0xd5, 0x5c, 0xf8, 0x1a, 0x4b, 0x28, 0x24, 0xd9, 0xd6, 0xa8, 0xde, 0x29, 0xdd, 0xf1,
	0xd4, 0x8f, 0x7e, 0x43, 0xb8, 0x84, 0x59, 0xb3, 0xd5, 0x43, 0xe7, 0xf8, 0xc4, 0x6f, 0x0a, 0x1d,
	0x9e, 0x02, 0x58, 0xa7, 0x4d, 0xf3, 0x4c, 0x8f, 0x4a, 0xf2, 0xa9, 0x9f, 0xcd, 0x03, 0x72, 0x23,
	0xab, 0x0f, 0x06, 0xb9, 0x20, 0xdb, 0xeb, 0xce, 0x12, 0x72, 0xc8, 0x5a, 0x43, 0x8d, 0xa3, 0xd1,
	0x4e, 0x2e, 0x62, 0x8b, 0x97, 0x90, 0x85, 0x40, 0xde, 0x56, 0xb1, 0x3e, 0xab, 0xff, 0xce, 0x59,
	0x87, 0x54, 0x22, 0xf2, 0xf1, 0x0a, 0xf2, 0x50, 0x5a, 0x9e, 0x96, 0xe9, 0x3e, 0xda, 0x6f, 0xc1,
	0xfa, 0x93, 0xc1, 0x22, 0xa0, 0x77, 0x23, 0x09, 0xef, 0xe1, 0xe8, 0xda, 0xbb, 0x8a, 0xf7, 0xf7,
	0xdf, 0xba, 0xe3, 0x72, 0x17, 0x21, 0x06, 0xaf, 0x0e, 0xf0, 0x01, 0x8a, 0x0d, 0xb9, 0xa0, 0xb0,
	0x58, 0xed, 0x92, 0xfc, 0xbc, 0xe1, 0x3e, 0x6b, 0x9f, 0x66, 0xfe, 0x53, 0x5c, 0x7c, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x86, 0x68, 0x45, 0x23, 0x33, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductService service

type ProductServiceClient interface {
	CreateProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error)
	GetProducts(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type productServiceClient struct {
	c           client.Client
	serviceName string
}

func NewProductServiceClient(serviceName string, c client.Client) ProductServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "steaks.product.service"
	}
	return &productServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *Product, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.CreateProduct", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.GetProducts", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	CreateProduct(context.Context, *Product, *Response) error
	GetProducts(context.Context, *GetRequest, *Response) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ProductService{hdlr}, opts...))
}

type ProductService struct {
	ProductServiceHandler
}

func (h *ProductService) CreateProduct(ctx context.Context, in *Product, out *Response) error {
	return h.ProductServiceHandler.CreateProduct(ctx, in, out)
}

func (h *ProductService) GetProducts(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ProductServiceHandler.GetProducts(ctx, in, out)
}
